# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import guessio_pb2 as guessio__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in guessio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GuessServiceStub(object):
    """gRPC Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinGame = channel.unary_unary(
                '/guessio.GuessService/JoinGame',
                request_serializer=guessio__pb2.JoinRequest.SerializeToString,
                response_deserializer=guessio__pb2.JoinReply.FromString,
                _registered_method=True)
        self.MakeGuess = channel.unary_unary(
                '/guessio.GuessService/MakeGuess',
                request_serializer=guessio__pb2.GuessRequest.SerializeToString,
                response_deserializer=guessio__pb2.GuessReply.FromString,
                _registered_method=True)


class GuessServiceServicer(object):
    """gRPC Service
    """

    def JoinGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeGuess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GuessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinGame': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinGame,
                    request_deserializer=guessio__pb2.JoinRequest.FromString,
                    response_serializer=guessio__pb2.JoinReply.SerializeToString,
            ),
            'MakeGuess': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeGuess,
                    request_deserializer=guessio__pb2.GuessRequest.FromString,
                    response_serializer=guessio__pb2.GuessReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'guessio.GuessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('guessio.GuessService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GuessService(object):
    """gRPC Service
    """

    @staticmethod
    def JoinGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/guessio.GuessService/JoinGame',
            guessio__pb2.JoinRequest.SerializeToString,
            guessio__pb2.JoinReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakeGuess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/guessio.GuessService/MakeGuess',
            guessio__pb2.GuessRequest.SerializeToString,
            guessio__pb2.GuessReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
