# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: guessio_grpc/guessio.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'guessio_grpc/guessio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aguessio_grpc/guessio.proto\x12\x0cguessio_grpc\"\x1f\n\x0bJoinRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\x1c\n\tJoinReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"/\n\x0cGuessRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05guess\x18\x02 \x01(\t\"+\n\nGuessReply\x12\x0f\n\x07\x63orrect\x18\x01 \x01(\x08\x12\x0c\n\x04hint\x18\x02 \x01(\t2\x91\x01\n\x0cGuessService\x12>\n\x08JoinGame\x12\x19.guessio_grpc.JoinRequest\x1a\x17.guessio_grpc.JoinReply\x12\x41\n\tMakeGuess\x12\x1a.guessio_grpc.GuessRequest\x1a\x18.guessio_grpc.GuessReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guessio_grpc.guessio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINREQUEST']._serialized_start=44
  _globals['_JOINREQUEST']._serialized_end=75
  _globals['_JOINREPLY']._serialized_start=77
  _globals['_JOINREPLY']._serialized_end=105
  _globals['_GUESSREQUEST']._serialized_start=107
  _globals['_GUESSREQUEST']._serialized_end=154
  _globals['_GUESSREPLY']._serialized_start=156
  _globals['_GUESSREPLY']._serialized_end=199
  _globals['_GUESSSERVICE']._serialized_start=202
  _globals['_GUESSSERVICE']._serialized_end=347
# @@protoc_insertion_point(module_scope)
